=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::AccountsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @instance = DialMyCalls::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instact of AccountsApi' do
      expect(@instance).to be_instance_of(DialMyCalls::AccountsApi)
    end
  end

  # unit tests for create_access_account
  # Add Access Account
  # Add a access account. &lt;br&gt;&lt;br&gt; Returns a access account object on success, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X POST -d \&quot;{\\\&quot;email\\\&quot;: \\\&quot;test@test.com\\\&quot;, \\\&quot;password\\\&quot;: \\\&quot;1234A5678\\\&quot;, \\\&quot;name\\\&quot;: \\\&quot;John Doe\\\&quot;}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/accessaccount &#x60;&#x60;&#x60;
  # @param create_access_account_parameters Request body
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_access_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_access_account_by_id
  # Delete Access Account
  # Delete a access account. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/accessaccount/$ACCESSACCOUNT_ID &#x60;&#x60;&#x60;
  # @param access_account_id AccessAccountId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_access_account_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_access_account_by_id
  # Get Access Account
  # Retrieve an access account. &lt;br&gt;&lt;br&gt; Returns a access account object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/accessaccount/$ACCESSACCOUNT_ID &#x60;&#x60;&#x60;
  # @param access_account_id AccessAccountId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_access_account_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_access_accounts
  # List Access Accounts
  # Retrieve a list of access accounts. &lt;br&gt;&lt;br&gt; Returns a list of access account objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/accessaccounts &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of accessaccounts requested
  # @return [Object]
  describe 'get_access_accounts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account
  # Get Account
  # Retrieve account details. &lt;br&gt;&lt;br&gt; Returns a account object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/account &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_access_account_by_id
  # Update Access Account
  # Update an existing access account. &lt;br&gt;&lt;br&gt; Returns a access account object if a valid identifier was provided and input validation passed, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X PUT -d \&quot;{\\\&quot;name\\\&quot;: \\\&quot;New Name\\\&quot;}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/accessaccount/$ACCESSACCOUNT_ID &#x60;&#x60;&#x60;
  # @param update_access_account_by_id_parameters Request body
  # @param access_account_id AccessAccountId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_access_account_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
