=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::CallsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallsApi' do
  before do
    # run before each test
    @instance = DialMyCalls::CallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallsApi' do
    it 'should create an instact of CallsApi' do
      expect(@instance).to be_instance_of(DialMyCalls::CallsApi)
    end
  end

  # unit tests for cancel_call_by_id
  # Cancel Call
  # Cancel an outgoing call. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/service/call/$CALL_ID &#x60;&#x60;&#x60;
  # @param call_id CallId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cancel_call_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_call
  # Create Call
  # Create an outgoing call broadcast. &lt;br&gt;&lt;br&gt; Returns a call service object on success, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X POST -d \&quot;{\\\&quot;name\\\&quot;: \\\&quot;Test\\\&quot;, \\\&quot;callerid_id\\\&quot;: \\\&quot;8bc6748e-d8a0-11e4-8b2d-00163e603cea\\\&quot;, \\\&quot;recording_id\\\&quot;: \\\&quot;079ff28a-1b75-11e5-88eb-00163e603cea\\\&quot;, \\\&quot;send_immediately\\\&quot;: true, \\\&quot;use_amd\\\&quot;: true, \\\&quot;contacts\\\&quot;: [{\\\&quot;phone\\\&quot;:\\\&quot;1116551235\\\&quot;},{\\\&quot;phone\\\&quot;:\\\&quot;1116551234\\\&quot;}]}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/service/call &#x60;&#x60;&#x60;
  # @param create_call_parameters Request body
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_call test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call_by_id
  # Get Call
  # Retrieve a call. &lt;br&gt;&lt;br&gt; Returns a call service object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/service/call/$CALL_ID &#x60;&#x60;&#x60;
  # @param call_id CallId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_call_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call_recipients_by_call_id
  # Get Call Recipients
  # Retrieve a list of a call&#39;s recipients. &lt;br&gt;&lt;br&gt; Returns a list of call recipient objects if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/service/call/$CALL_ID/recipients &#x60;&#x60;&#x60;
  # @param call_id CallId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of recipients requested
  # @return [Object]
  describe 'get_call_recipients_by_call_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_calls
  # List Calls
  # Retrieve a list of calls. &lt;br&gt;&lt;br&gt; Returns a list of call service objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/service/calls &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of calls requested
  # @return [Object]
  describe 'get_calls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
