=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::DoNotContactsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DoNotContactsApi' do
  before do
    # run before each test
    @instance = DialMyCalls::DoNotContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DoNotContactsApi' do
    it 'should create an instact of DoNotContactsApi' do
      expect(@instance).to be_instance_of(DialMyCalls::DoNotContactsApi)
    end
  end

  # unit tests for get_do_not_contacts
  # List DoNotContacts
  # Retrieve a list of donotcontacts. &lt;br&gt;&lt;br&gt; Returns a list of donotcontact objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/donotcontacts &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of donotcontacts requested
  # @return [Object]
  describe 'get_do_not_contacts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
