=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::GroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @instance = DialMyCalls::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instact of GroupsApi' do
      expect(@instance).to be_instance_of(DialMyCalls::GroupsApi)
    end
  end

  # unit tests for create_group
  # Add Group
  # Add a contact group. &lt;br&gt;&lt;br&gt; Returns a group object on success, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X POST -d \&quot;{\\\&quot;name\\\&quot;: \\\&quot;Test Group\\\&quot;}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/group &#x60;&#x60;&#x60;
  # @param create_group_parameters Request body
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_group test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_group_by_id
  # Delete Group
  # Delete a contact group. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/group/$GROUP_ID &#x60;&#x60;&#x60;
  # @param group_id GroupId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_group_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_group_by_id
  # Get Group
  # Retrieve a contact group. &lt;br&gt;&lt;br&gt; Returns a group object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/group/$GROUP_ID &#x60;&#x60;&#x60;
  # @param group_id GroupId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_group_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_groups
  # List Groups
  # Retrieve a list of contact groups. &lt;br&gt;&lt;br&gt; Returns a list of group objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/groups &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of groups requested
  # @return [Object]
  describe 'get_groups test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_group_by_id
  # Update Group
  # Update an existing contact group. &lt;br&gt;&lt;br&gt; Returns a group object if a valid identifier was provided and input validation passed, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X PUT -d \&quot;{\\\&quot;name\\\&quot;: \\\&quot;Test Group Updated\\\&quot;}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/group/$GROUP_ID &#x60;&#x60;&#x60;
  # @param update_group_by_id_parameters Request body
  # @param group_id GroupId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_group_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
