=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::KeywordsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KeywordsApi' do
  before do
    # run before each test
    @instance = DialMyCalls::KeywordsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeywordsApi' do
    it 'should create an instact of KeywordsApi' do
      expect(@instance).to be_instance_of(DialMyCalls::KeywordsApi)
    end
  end

  # unit tests for delete_keyword_by_id
  # Delete Keyword
  # Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
  # @param keyword_id KeywordId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_keyword_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_keyword_by_id
  # Get Keyword
  # Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
  # @param keyword_id KeywordId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_keyword_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_keywords
  # List Keywords
  # Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested
  # @return [Object]
  describe 'get_keywords test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
