=begin
#DialMyCalls API

#The DialMyCalls API

OpenAPI spec version: 2.0.1
Contact: support@dialmycalls.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DialMyCalls::VanityNumbersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VanityNumbersApi' do
  before do
    # run before each test
    @instance = DialMyCalls::VanityNumbersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VanityNumbersApi' do
    it 'should create an instact of VanityNumbersApi' do
      expect(@instance).to be_instance_of(DialMyCalls::VanityNumbersApi)
    end
  end

  # unit tests for delete_vanity_number_by_id
  # Delete Vanity Number
  # Delete a vanity number. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$VANITYNUMBER_ID &#x60;&#x60;&#x60;
  # @param vanity_number_id VanityNumberId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_vanity_number_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vanity_number_by_id
  # Get Vanity Number
  # Retrieve a vanity number. &lt;br&gt;&lt;br&gt; Returns a vanitynumber object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/vanitynumber/$VANITYNUMBER_ID &#x60;&#x60;&#x60;
  # @param vanity_number_id VanityNumberId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_vanity_number_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vanity_numbers
  # List Vanity Numbers
  # Retrieve a list of vanity numbers. &lt;br&gt;&lt;br&gt; Returns a list of vanitynumber objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/vanitynumbers &#x60;&#x60;&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Range (ie \&quot;records&#x3D;201-300\&quot;) of vanitynumbers requested
  # @return [Object]
  describe 'get_vanity_numbers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_vanity_number_by_id
  # Update Vanity Number
  # Update a vanity number. &lt;br&gt;&lt;br&gt; Returns a vanitynumber object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X PUT -d \&quot;{\\\&quot;ptt_number_id\\\&quot;:\\\&quot;aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee\\\&quot;,\\\&quot;call_options\\\&quot;:{\\\&quot;voicemail\\\&quot;:true}}\&quot; https://$API_KEY@api.dialmycalls.com/2.0/vanitynumber/$VANITYNUMBER_ID &#x60;&#x60;&#x60;
  # @param update_vanity_number_by_id_parameters Request body
  # @param vanity_number_id VanityNumberId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_vanity_number_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
